### ISSUE TITLE
Fails when using `Optional` annotation for a 

### ISSUE THREAD

**Issue by ivergara** [abatilo/typed-json-dataclass#4]
### Subject of the issue
If the dataclass with the `TypedJsonMixin` has a attribute with `None` as default value, and you want to properly annotate for mypy, the dataclass becomes unusable.

### Steps to reproduce
Here is the code to reproduce the situation

```python
from dataclasses import dataclass
from typing import Optional
from typed_json_dataclass import TypedJsonMixin

@dataclass
class Person(TypedJsonMixin):
    name: str
    age: Optional[int] = None

Person("John", 42)
```

### Expected behaviour
Would have expected it to still be usable. Perhaps it is desired behavior due to how json is specified, and as such a non-issue. But maybe you're still interested in such a report.

### Actual behaviour
Ends up raising
> TypeError: typing.Union cannot be used with isinstance()

because under the hood `Optional` is a particular type `Union[NonType, int]`.

Post Scriptum: Nice project and very clear coding! Good job.

**Comment by abatilo** [comment]
Hey @ivergara!

Thank you so much for taking the time to report this issue. I've addressed this in the following commit:
https://github.com/abatilo/typed-json-dataclass/commit/f71809f0e18bfaaa20a51785e717a0a0bc3a057d

And version 0.2.2 should be available on PyPI shortly.

Reminder that the `to_dict` and `to_json` methods have a keyword parameter for `keep_none` for handling whether or not you want to expose that some of these variables are in fact undefined.
